### ISSUE TITLE
运行mesher.exe报错提示

### ISSUE THREAD

**Issue by wz1002335** [apache/servicecomb-mesher#133]
failed: Get \"http:///v4/default/registry/existence?type=microservice\u0026appId=defau
lt\u0026serviceName=calculator\u0026version=1.1.1\": http: no Host in request URL"}

根据快速入门操作，运行mesher.exe，注册中心没有对应服务。

**Comment by tianxiaoliang** [comment]
http:///v4/default明显是没有配置注册中心地址

看下示例https://github.com/apache/servicecomb-mesher/blob/master/conf/chassis.yaml

**Comment by wz1002335** [comment]
根据快速入门操作的，注册中心有配置的，没有漏操作，注册中心配置的是127.0.0.1:30100。
后面根据示例全改成127.0.0.1，运行结果还是一样

**Comment by wz1002335** [comment]
我将示例的classis.yaml全部替换，能够注册到注册中心。快速入门demo调用报错

arrPara : /calculator/bmi,height=180&weight=70
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.<anonymous> (E:\test\mesher\servicecomb-mesher-master\examples\quick_start\httpserver_webapp\httpserver_webapp.js:44:19)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:677:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
